version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    working_dir: /code
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - jrdnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - jrdnet

networks:
  jrdnet:
